//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int Id { get; set; }
        public int Vid { get; set; }
        public int Sort { get; set; }
        public int Flag { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Url { get; set; }
        public string Path { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
